# Main docker-compose file that orchestrates all services
version: '3.8'

services:
  # n8n automation service
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      #start_period:: 20s

  # Nginx service to route traffic
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx/ssl:/etc/nginx/ssl:ro
      - ./landing/dist:/usr/share/nginx/html:ro
      #- ./nginx/error:/usr/share/nginx/html/error:ro
    depends_on:
      - n8n
      - landing
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Landing page service for production
  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
    restart: unless-stopped
    command: npx serve -s dist
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    volumes:
      - ./landing/dist:/app/dist:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # WordPress service - commented out for now
  # wordpress:
  #   extends:
  #     file: ./wp_start/docker-compose.yml
  #     service: wordpress
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  n8n_data:
    driver: local