version: '3.8'

services:
  # Development mode service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - .:/app
      - /app/node_modules  # Exclude node_modules from mounting
      - /app/dist  # Exclude dist from mounting
    ports:
      - "5174:5173"  # Vite dev server
      - "3000:3000"  # Express API server
    environment:
      - NODE_ENV=development
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    command: sh -c "npm run dev -- --host 0.0.0.0 & node server/index.js & wait"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Build-only service for CI/CD pipelines
  build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      args:
        - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
        - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    volumes:
      - dist_data:/app/dist
    environment:
      - NODE_ENV=production
      - VITE_TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - VITE_TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    command: >
      sh -c "
        mkdir -p /app/dist &&
        npm run build &&
        echo 'Build completed. Copying to volume...'
      "

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
        - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - PORT=3000
    volumes:
      - dist_data:/app/dist:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Nginx service for production
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - dist_data:/usr/share/nginx/html:ro
    depends_on:
      - prod
    environment:
      - NGINX_HOST=akane.production
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 1m
      timeout: 5s
      retries: 3

volumes:
  dist_data:
    name: akane_landing_dist_data
