services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5174:5173"
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    command: sh -c "npm run dev -- --host 0.0.0.0 & node server/index.js & wait"

  build:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run build
    volumes:
      - dist_data:/app/dist
    environment:
      - NODE_ENV=production
      - VITE_TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - VITE_TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: node server/index.js
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - VITE_TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    volumes:
      - dist_data:/app/dist:ro

volumes:
  dist_data:
