# Landing page docker-compose file
version: '3.8'

services:
  # Development service with hot-reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5174:5173"
    environment:
      - NODE_ENV=development
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5173"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Build service for creating production assets
  build:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run build
    volumes:
      - dist_data:/app/dist
    environment:
      - NODE_ENV=production
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}

  # Production service to serve static files
  serve:
    build:
      context: .
      dockerfile: Dockerfile
    command: npx serve -s dist
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    volumes:
      - dist_data:/app/dist:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  
volumes:
  dist_data:
