# Simplified landing page docker-compose file
version: '3.8'

services:
  # Combined development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5174:5173" # Vite dev server
      - "3000:3000" # API server
    environment:
      - NODE_ENV=development
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    command: sh -c "npm run dev -- --host 0.0.0.0 & node server/index.js & wait"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Build service for creating production assets
  build:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run build
    volumes:
      - dist_data:/app/dist
    environment:
      - NODE_ENV=production
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}

  # Production service (combined server)
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: node server/index.js
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    volumes:
      - dist_data:/app/dist:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  
volumes:
  dist_data: