# Updated docker-compose.yml for landing directory
services:
  # Development environment with hot reloading
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      # Mount the source code for development
      - .:/app:delegated
      # Use Docker volume for node_modules for better performance
      - node_modules:/app/node_modules
    ports:
      - "${DEV_PORT:-5173}:5173"
      - "${API_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      # Properly pass both TWITCH_CLIENT_ID and VITE_TWITCH_CLIENT_ID
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - VITE_TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      # Vite optimization settings
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      # Performance tuning
      - NODE_OPTIONS="--max-old-space-size=2048"
    command: >
      sh -c "
        echo 'Starting development servers...' &&
        echo 'TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}' &&
        npm run dev -- --host 0.0.0.0 & 
        node server/index.js & 
        wait
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  # Build service - outputs directly to shared host directory
  build:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
        - VITE_TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
    volumes:
      - ./dist:/app/dist
    environment:
      - NODE_ENV=production
      # Properly pass both TWITCH_CLIENT_ID and VITE_TWITCH_CLIENT_ID
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - VITE_TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      # Optimize build performance
      - NODE_OPTIONS="--max-old-space-size=4096"
      - VITE_BUILD_MINIFY=true
      - VITE_BUILD_SOURCEMAP=false
    command: >
      sh -c "
        echo 'Building with TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}' &&
        npm run build
      "
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 4G

  # Standalone server for testing production build
  serve:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
        - VITE_TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
    ports:
      - "${SERVE_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      # Properly pass both TWITCH_CLIENT_ID and VITE_TWITCH_CLIENT_ID
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - VITE_TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - PORT=3000
      # Enable compression and caching
      - ENABLE_COMPRESSION=true
      - HTTP_CACHE_CONTROL="public, max-age=86400"
    volumes:
      - ./dist:/app/dist:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

# Named volume for node_modules in development
volumes:
  node_modules: