version: '3.8'

services:
  # Development environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - /app/dist
    ports:
      - "${DEV_PORT:-5173}:5173"
      - "${API_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=5173
    command: >
      sh -c "
        echo 'Starting development servers...' &&
        npm run dev -- --host 0.0.0.0 & 
        node server/index.js & 
        wait
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Build service
  build:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - dist_data:/app/dist
    environment:
      - NODE_ENV=production
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
    command: >
      sh -c "
        mkdir -p /app/dist &&
        npm run build &&
        cp -r dist/* /app/dist/ &&
        chmod -R 755 /app/dist &&
        echo 'Build completed successfully'
      "

  # Standalone server for testing production build
  serve:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${SERVE_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - PORT=3000
    volumes:
      - dist_data:/app/dist:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  dist_data:
    name: akane_dist_data